# Generated by Django 2.1.1 on 2018-10-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twitch_username',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
